[package]
name = "data_lineage_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "0.20"
tree-sitter-graph = "0.11"
tree-sitter-javascript = "0.20"
tempfile = "3.2"

[dev-dependencies]
tempfile = "3.8"
pretty_assertions = "1.4"